const fortunes = [
    // School and Learning
    "Your curiosity will lead you to amazing discoveries today!",
    "Every question you ask makes you even smarter.",
    "Today you will learn something exciting and new.",
    "Your brain grows stronger every time you try.",
    "Being curious about the world makes life exciting.",
    "Your imagination will help solve today's challenges well.",
    "Reading opens up whole new worlds for you.",
    "Making mistakes helps you learn amazing new things.",
    "Your creative ideas will make learning fun today.",
    "Every day brings a new chance to learn.",

    // Friendship and Kindness
    "Your kindness will brighten someone's day very much.",
    "A new friendship will bring joy to you.",
    "Someone will appreciate your helpful nature today.",
    "Your smile will make others happy today.",
    "Being a good friend makes life more fun.",
    "Your kind words will help someone feel better.",
    "Sharing with others brings happiness to everyone.",
    "Your friendly nature helps others feel welcome.",
    "Making new friends will be easy today.",
    "Your friendship means the world to someone.",

    // Family and Home
    "Your family loves watching you grow and learn.",
    "Helping at home makes everyone's day better.",
    "Your family appreciates all that you do.",
    "Today you will make your family smile.",
    "Your home is filled with love and joy.",
    "Being helpful at home brings everyone happiness.",
    "Your family is proud of who you are.",
    "Simple acts of kindness make home wonderful.",
    "Today you will share special moments together.",
    "Your home is where great memories happen.",

    // Sports and Activities
    "Practice makes every skill better and stronger.",
    "Your determination helps you improve every day.",
    "Having fun while playing makes you even better.",
    "Your energy will inspire others to join in.",
    "Today's practice will make tomorrow even better.",
    "Your teamwork skills make games more fun.",
    "Every time you try, you get stronger.",
    "Playing fair makes victories even more special.",
    "Your positive attitude makes everyone play better.",
    "Having fun is the best way to improve.",

    // Nature and Animals
    "Your love for animals makes the world better.",
    "Nature has wonderful surprises in store today.",
    "Being kind to animals brings special happiness.",
    "Your care for nature will inspire others.",
    "Today you will discover something amazing outside.",
    "Watching animals teaches us about being kind.",
    "Your gentle heart helps protect our planet.",
    "Nature's wonders are waiting for you today.",
    "Being outside will bring you joy today.",
    "Your respect for nature makes Earth happier.",

    // Creativity and Art
    "Your imagination will create something amazing today.",
    "Colors and shapes become magical through you.",
    "Your art will make people feel happy.",
    "Creating something new brings special kind of joy.",
    "Your artistic ideas will inspire others today.",
    "Making art helps share your wonderful thoughts.",
    "Your creative spirit makes the world beautiful.",
    "Drawing and coloring brings happiness to everyone.",
    "Your unique ideas make art extra special.",
    "Today your creativity will shine very bright.",

    // Problem Solving
    "You can solve any puzzle you try.",
    "Your clever mind finds wonderful new solutions.",
    "Working through challenges makes you even stronger.",
    "Your problem-solving skills grow every single day.",
    "Taking your time helps find the best answer.",
    "Your mind is full of brilliant solutions.",
    "Every problem has an answer you can find.",
    "Your patient thinking leads to great solutions.",
    "Breaking big problems into small ones helps.",
    "Your determination helps solve tricky problems well.",

    // Personal Growth
    "Every day you grow a little stronger.",
    "Your best effort makes everything worthwhile.",
    "Being yourself brings out your special talents.",
    "Your courage grows stronger every single day.",
    "Trying new things helps you discover yourself.",
    "Your unique qualities make you extra special.",
    "Each day brings chances to be your best.",
    "Your confidence grows when you keep trying.",
    "Being brave helps you learn new things.",
    "Your heart knows the right thing always.",

    // Helping Others
    "Helping others makes everyone's day much better.",
    "Your kindness creates ripples of good feelings.",
    "Small helpful actions make big positive changes.",
    "Your caring heart makes others feel special.",
    "Being helpful brings happiness to everyone around.",
    "Your actions inspire others to be kind.",
    "Helping someone today will bring double joy.",
    "Your generous spirit lifts everyone's mood up.",
    "Small acts of kindness create big smiles.",
    "Your helpfulness makes the world much better.",

    // Reading and Stories
    "Books will take you on amazing adventures today.",
    "Your love of reading opens magical new worlds.",
    "Stories help your imagination grow even bigger.",
    "Your mind creates wonderful pictures while reading.",
    "Reading helps you discover exciting new things.",
    "Your curiosity makes every story an adventure.",
    "Books are like friends waiting to meet you.",
    "Your reading adventures will be exciting today.",
    "Stories help your imagination soar very high.",
    "Your reading journey brings wonderful discoveries today.",

    // Music and Dance
    "Your music brings joy to everyone around.",
    "Dancing makes your heart happy and strong.",
    "Your rhythm makes others want to dance.",
    "Making music helps share happiness with others.",
    "Your songs make the world more beautiful.",
    "Moving to music makes everything more fun.",
    "Your musical spirit brings smiles to others.",
    "Dancing helps your happiness grow even bigger.",
    "Your voice adds beauty to the world.",
    "Music makes your heart feel extra special.",

    // Science and Discovery
    "Your experiments will lead to exciting discoveries.",
    "Asking questions helps you understand new things.",
    "Your curiosity about science creates new learning.",
    "Exploring how things work is very exciting.",
    "Your scientific mind makes discoveries every day.",
    "Learning about science opens up new worlds.",
    "Your questions lead to amazing new answers.",
    "Science helps you understand wonderful things.",
    "Your discoveries will surprise and delight you.",
    "Exploring nature teaches you amazing new things.",

    // Writing and Expression
    "Your words will tell wonderful stories today.",
    "Writing helps share your amazing thoughts clearly.",
    "Your stories will take readers on adventures.",
    "Expressing yourself through writing brings joy.",
    "Your ideas make wonderful stories come alive.",
    "Writing helps your imagination grow even bigger.",
    "Your unique voice makes stories extra special.",
    "Sharing your thoughts through writing helps others.",
    "Your writing creates magical new worlds today.",
    "Stories from your heart touch other hearts.",

    // Math and Numbers
    "Numbers are like friends you understand well.",
    "Your math skills grow stronger every day.",
    "Solving number puzzles makes your mind sharp.",
    "Your patient work in math brings success.",
    "Math helps you understand the world better.",
    "Your number sense grows stronger each day.",
    "Working with numbers makes your mind strong.",
    "Your math practice leads to great understanding.",
    "Numbers tell interesting stories through you.",
    "Your mathematical thinking solves daily puzzles well.",

    // Games and Fun
    "Playing fairly makes games more fun always.",
    "Your playful spirit helps others have fun.",
    "Games help you learn while having fun.",
    "Your positive attitude makes playing more enjoyable.",
    "Having fun while learning makes everything better.",
    "Your enthusiasm makes games more exciting always.",
    "Playing together creates wonderful new friendships.",
    "Your love of games brings people together.",
    "Fun and laughter make learning even better.",
    "Your playful nature helps others join in.",

    // Future and Dreams
    "Your dreams will guide you to amazing places.",
    "Believing in yourself makes dreams come true.",
    "Your future is bright with endless possibilities.",
    "Today's efforts create tomorrow's wonderful achievements.",
    "Your dreams help make the world better.",
    "Working toward goals brings wonderful rewards.",
    "Your future holds many exciting new adventures.",
    "Dreams give you strength to try again.",
    "Your hopes make the future look bright.",
    "Today's small steps lead to big dreams.",

    // Courage and Strength
    "Your courage helps you try new things.",
    "Being brave means doing your very best.",
    "Your strength grows with every challenge faced.",
    "Standing up for others shows great courage.",
    "Your brave heart helps others feel strong.",
    "Every day your courage grows even stronger.",
    "Your inner strength helps overcome any challenge.",
    "Being brave means asking for help too.",
    "Your courage inspires others to be brave.",
    "Each challenge makes your heart more courageous.",

    // Happiness and Joy
    "Your smile brightens everyone's day around you.",
    "Joy finds you in the simplest moments.",
    "Your happiness helps others feel good too.",
    "Sharing laughter makes everyone's day much better.",
    "Your cheerful spirit lifts others up high.",
    "Finding joy in small things brings happiness.",
    "Your positive attitude spreads happiness everywhere.",
    "Simple pleasures bring the greatest joy today.",
    "Your joyful spirit makes others feel happy.",
    "Happiness grows when you share it freely.",

    // Health and Energy
    "Taking care of yourself brings endless energy.",
    "Your healthy choices make you feel great.",
    "Moving your body brings strength and joy.",
    "Your energy helps others feel more alive.",
    "Healthy habits make every day more fun.",
    "Your active lifestyle keeps you feeling wonderful.",
    "Taking good care makes your body strong.",
    "Your healthy choices inspire others too.",
    "Exercise makes your whole day much better.",
    "Your body grows stronger with good care."
];